# Generated by Django 4.2.7 on 2023-11-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_profileuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='text_big',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
