# Generated by Django 4.2.7 on 2023-11-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_classroom_test_alter_lessons_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='category',
            new_name='classroom',
        ),
    ]
