# Generated by Django 4.2.7 on 2023-11-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_options_text_big'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text_big',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='options',
            name='text_big',
            field=models.TextField(blank=True, null=True),
        ),
    ]
