# Generated by Django 4.2.7 on 2023-11-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_question_text_big_alter_options_text_big'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text_big',
        ),
    ]
