# Generated by Django 4.2.7 on 2023-11-14 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0007_remove_options_text_big'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
