# Generated by Django 4.2.7 on 2023-11-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
