# Generated by Django 4.2.7 on 2023-11-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_options_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
