# Generated by Django 4.2.7 on 2023-11-12 13:30

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_options_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1, validators=[lms.models.validate_non_negative]),
        ),
    ]
